-- Astrans Phase 1 extras. Does not alter stock ITEMS/CONTACTS/SALES_INVOICES columns.
CREATE TABLE IF NOT EXISTS ASTRANS_ITEM_EXTRAS (
  ITEM_ID INT UNSIGNED NOT NULL PRIMARY KEY,
  PACK_SIZE_LITRES DECIMAL(13,4) NULL,
  SUBCATEGORY VARCHAR(255) NULL,
  UPDATED_AT DATETIME NULL
);

CREATE TABLE IF NOT EXISTS ASTRANS_CONTACT_EXTRAS (
  CONTACT_ID INT UNSIGNED NOT NULL PRIMARY KEY,
  VAT_TIN VARCHAR(32) NULL,
  AREA_NAME VARCHAR(255) NULL,
  AREA_QQ VARCHAR(8) NULL,
  CREDIT_CATEGORY CHAR(1) NOT NULL DEFAULT 'B',
  UPDATED_AT DATETIME NULL
);

CREATE TABLE IF NOT EXISTS ASTRANS_INVOICE_EXTRAS (
  INVOICE_ID INT UNSIGNED NOT NULL PRIMARY KEY,
  OPS_STATUS VARCHAR(32) NOT NULL DEFAULT 'pending',
  ASSIGNED_NUMBER VARCHAR(64) NULL,
  UPDATED_AT DATETIME NULL
);
